#!/usr/bin/env bash
# Function to display information for a specific subdomain
domain_information() {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    domain_information "$2.$1" "$2"
else
    domain_information "www.$1" "www"
    domain_information "lb-01.$1" "lb-01"
    domain_information "web-01.$1" "web-01"
    domain_information "web-02.$1" "web-02"
fi
