#!/usr/bin/env bash
# Function to display information for a specific subdomain
domain_information() {
    local domain="$1"
    local subdomain="$2"
    line=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
    echo "$subdomain $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}

# Main script
if [ "$#" -eq 1 ]; then
    domain="$1"
    domain_information "$domain" www
    domain_information "$domain" lb-01
    domain_information "$domain" web-01
    domain_information "$domain" web-02
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi
