#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx

sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
