#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.234.97.54-web-01:80 check
    server web-02 100.25.190.116-web-02:80 check
EOF

# Verify configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
