#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# edit config file
server_config=\
"
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.234.97.54-web-01:80 check
    server web-02 100.25.190.116-web-02:80 check
"

# Verify configuration
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy
echo "ENABLED=1" | sudo tee -a /etc/haproxy/haproxy

#test
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo service haproxy restart
