#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Configure Nginx to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
