#!/usr/bin/env bash
# This script tells the story of /etc/passwd using a while loop + IFS

passwd_file="/etc/passwd"

while IFS=: read -r username _ userid groupid _ homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < "$passwd_file"
