#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

for file in *; do
    if [[ ! $file =~ ^\. && -f $file ]]; then
        display_name=$(echo "$file" | cut -d'-' -f2-)

        echo "$display_name"
    fi
done
