#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su -s /bin/bash nginx -c 'service nginx restart'
